# Generated by Django 4.1.5 on 2023-04-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_decription_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_video',
        ),
    ]
